<?php

declare(strict_types = 1);

use Illuminate\Database\Seeder;

class ProgramLogTableSeeder extends AppSeeder
{
    private $program_log;

    public function __construct(
        \App\Services\ProgramLogService $program_log
    ) {
        $this->program_log = $program_log;
    }

    public function run()
    {
        DB::table('program_logs')->delete();

        $program_logs = [
            ['programId' => 1, 'price' => 100],
            ['programId' => 1, 'price' => 110],
            ['programId' => 1, 'price' => 120],
            ['programId' => 1, 'price' => 130],
            ['programId' => 1, 'price' => 140],
            ['programId' => 1, 'price' => 130],
            ['programId' => 1, 'price' => 120],
            ['programId' => 1, 'price' => 200],
            ['programId' => 1, 'price' => 300],
            ['programId' => 1, 'price' => 500],
            ['programId' => 1, 'price' => 100],
            ['programId' => 1, 'price' => 110],
            ['programId' => 1, 'price' => 120],
            ['programId' => 1, 'price' => 130],
            ['programId' => 1, 'price' => 140],
            ['programId' => 1, 'price' => 130],
            ['programId' => 1, 'price' => 120],
            ['programId' => 1, 'price' => 200],
            ['programId' => 1, 'price' => 300],
            ['programId' => 1, 'price' => 500],
            ['programId' => 1, 'price' => 100],
            ['programId' => 1, 'price' => 100],
            ['programId' => 1, 'price' => 110],
            ['programId' => 1, 'price' => 120],
            ['programId' => 1, 'price' => 130],
            ['programId' => 1, 'price' => 140],
            ['programId' => 1, 'price' => 130],
            ['programId' => 1, 'price' => 120],
            ['programId' => 1, 'price' => 200],
            ['programId' => 1, 'price' => 300],
            ['programId' => 1, 'price' => 500],
            ['programId' => 1, 'price' => 100],
            ['programId' => 2, 'price' => 100],
            ['programId' => 2, 'price' => 110],
            ['programId' => 2, 'price' => 120],
            ['programId' => 2, 'price' => 130],
            ['programId' => 2, 'price' => 140],
            ['programId' => 2, 'price' => 130],
            ['programId' => 2, 'price' => 120],
            ['programId' => 2, 'price' => 200],
            ['programId' => 2, 'price' => 300],
            ['programId' => 2, 'price' => 500],
            ['programId' => 2, 'price' => 100],
            ['programId' => 2, 'price' => 100],
            ['programId' => 2, 'price' => 110],
            ['programId' => 2, 'price' => 120],
            ['programId' => 2, 'price' => 130],
            ['programId' => 2, 'price' => 140],
            ['programId' => 2, 'price' => 130],
            ['programId' => 2, 'price' => 120],
            ['programId' => 2, 'price' => 200],
            ['programId' => 2, 'price' => 300],
            ['programId' => 2, 'price' => 500],
            ['programId' => 2, 'price' => 100],
            ['programId' => 2, 'price' => 100],
            ['programId' => 2, 'price' => 110],
            ['programId' => 2, 'price' => 120],
            ['programId' => 2, 'price' => 130],
            ['programId' => 2, 'price' => 140],
            ['programId' => 2, 'price' => 130],
            ['programId' => 2, 'price' => 120],
            ['programId' => 2, 'price' => 200],
            ['programId' => 2, 'price' => 300],
            ['programId' => 2, 'price' => 500],
            ['programId' => 2, 'price' => 100],
            ['programId' => 3, 'price' => 110],
            ['programId' => 3, 'price' => 120],
            ['programId' => 3, 'price' => 130],
            ['programId' => 3, 'price' => 140],
            ['programId' => 3, 'price' => 130],
            ['programId' => 3, 'price' => 220],
            ['programId' => 3, 'price' => 200],
            ['programId' => 3, 'price' => 300],
            ['programId' => 3, 'price' => 500],
            ['programId' => 3, 'price' => 110],
            ['programId' => 3, 'price' => 120],
            ['programId' => 3, 'price' => 130],
            ['programId' => 3, 'price' => 140],
            ['programId' => 3, 'price' => 130],
            ['programId' => 3, 'price' => 220],
            ['programId' => 3, 'price' => 130],
            ['programId' => 3, 'price' => 140],
            ['programId' => 3, 'price' => 130],
            ['programId' => 3, 'price' => 220],
            ['programId' => 3, 'price' => 200],
            ['programId' => 3, 'price' => 300],
            ['programId' => 3, 'price' => 500],
            ['programId' => 3, 'price' => 110],
            ['programId' => 3, 'price' => 120],
            ['programId' => 3, 'price' => 130],
            ['programId' => 3, 'price' => 140],
            ['programId' => 3, 'price' => 130],
            ['programId' => 3, 'price' => 220],
            ['programId' => 3, 'price' => 200],
            ['programId' => 3, 'price' => 300],
            ['programId' => 3, 'price' => 500],
            ['programId' => 4, 'price' => 100],
            ['programId' => 4, 'price' => 110],
            ['programId' => 4, 'price' => 120],
            ['programId' => 4, 'price' => 140],
            ['programId' => 4, 'price' => 140],
            ['programId' => 4, 'price' => 140],
            ['programId' => 4, 'price' => 220],
            ['programId' => 4, 'price' => 200],
            ['programId' => 4, 'price' => 400],
            ['programId' => 4, 'price' => 500],
            ['programId' => 4, 'price' => 100],
            ['programId' => 4, 'price' => 140],
            ['programId' => 4, 'price' => 140],
            ['programId' => 4, 'price' => 140],
            ['programId' => 4, 'price' => 140],
            ['programId' => 4, 'price' => 140],
            ['programId' => 4, 'price' => 220],
            ['programId' => 4, 'price' => 200],
            ['programId' => 4, 'price' => 400],
            ['programId' => 4, 'price' => 200],
            ['programId' => 4, 'price' => 400],
            ['programId' => 4, 'price' => 500],
            ['programId' => 4, 'price' => 100],
            ['programId' => 4, 'price' => 140],
            ['programId' => 4, 'price' => 140],
            ['programId' => 4, 'price' => 140],
            ['programId' => 4, 'price' => 140],
            ['programId' => 4, 'price' => 140],
            ['programId' => 4, 'price' => 220],
            ['programId' => 4, 'price' => 200],
            ['programId' => 4, 'price' => 400],
            ['programId' => 4, 'price' => 500],
            ['programId' => 4, 'price' => 100],
            ['programId' => 4, 'price' => 140],
            ['programId' => 4, 'price' => 140],
            ['programId' => 4, 'price' => 140],
            ['programId' => 4, 'price' => 220],
            ['programId' => 4, 'price' => 200],
            ['programId' => 4, 'price' => 400],
            ['programId' => 4, 'price' => 500],
            ['programId' => 4, 'price' => 100],
        ];

        foreach ($program_logs as $index => $log) {
            $logData = $this->program_log->create($log['programId'], $log['programId']);
            $this->changeId($logData, $index + 1);
        }
    }
}
